name: osm_navigator
description: OSM-based GNSS navigation using MapLibre + OSRM + Nominatim.
version: 0.1.5+6
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  maplibre_gl: ^0.22.0
  geolocator: ^13.0.1
  http: ^1.2.2
  intl: ^0.19.0

flutter:
  uses-material-design: true
