name: saitis_nav
description: SAITIS NAV - full GitHub project (v26)
publish_to: 'none'
version: 26.0.0+26

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  maplibre_gl: ^0.24.0

flutter:
  uses-material-design: true
