name: saitis_nav
description: SAITIS NAV - consolidated full project (GitHub workflow uses Flutter CLI)
publish_to: 'none'
version: 23.0.0+23

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  maplibre_gl: ^0.24.0

flutter:
  uses-material-design: true
