name: saitis_nav
description: SAITIS NAV - final consolidated full project
publish_to: 'none'
version: 22.0.0+22

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  maplibre_gl: ^0.24.0
  geolocator: ^11.0.0
  flutter_tts: ^3.8.5
  permission_handler: ^11.4.0
  shared_preferences: ^2.3.2
  package_info_plus: ^8.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/triangle.png
    - assets/images/dest.png
