name: Android APK
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          java-version: '21'

      - name: Verify project root
        run: |
          test -f pubspec.yaml || (echo 'pubspec.yaml not found in repo root' >&2; exit 1)
          test -d lib || (echo 'lib/ folder not found in repo root' >&2; exit 1)

      - name: Flutter clean & pub get
        run: |
          flutter clean
          flutter pub get

      - name: Build APK (Flutter CLI)
        run: |
          flutter build apk --release --no-tree-shake-icons --verbose
          echo "=== APKs found ==="
          find build -type f -name "*.apk" -print || true

      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: |
            build/**/outputs/**/*.apk
            build/**/*.apk
          if-no-files-found: error
