name: Android APK
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          java-version: '21'

      - name: Detect Flutter project dir
        id: detect
        shell: bash
        run: |
          set -e
          CANDIDATE="$(find "$GITHUB_WORKSPACE" -maxdepth 5 -type f -name pubspec.yaml | head -n1)"
          if [ -z "$CANDIDATE" ]; then
            echo "pubspec.yaml not found within $GITHUB_WORKSPACE" >&2
            exit 1
          fi
          PROJECT_DIR="$(dirname "$CANDIDATE")"
          echo "PROJECT_DIR=$PROJECT_DIR" >> $GITHUB_ENV
          echo "Detected project dir: $PROJECT_DIR"

      - name: Flutter pub get
        working-directory: ${{ env.PROJECT_DIR }}
        run: flutter pub get

      - name: Build APK (Flutter CLI)
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          flutter clean
          flutter build apk --release --no-tree-shake-icons --verbose --no-pub
          echo "=== APKs found (repo-wide) ==="
          find . -type f -name "*.apk" -print || true

      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: |
            ${{ env.PROJECT_DIR }}/**/*.apk
            **/*.apk
          if-no-files-found: warn
